### ISSUE TITLE
Please, help

### ISSUE THREAD

**Issue by balezej** [oxullo/mml#1]
Is any chance to contact with you? I have some trouble with MAX30100. I did a research, and i saw that u could help me. Please, you are my last hope. Text me on blazej.rosolowski@gmail.com

**Comment by oxullo** [comment]
Hey @balezej 
you hit the wrong project for an issue report. Please file an issue here https://github.com/oxullo/Arduino-MAX30100/issues if you haven't done so and see if the community can support. Unfortunately I have limited time availability and the MAX30100 has been EOL for a while
